// This file was generated by Mendix Modeler 6.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package testtwitterconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TestTwitterConnector module
	public static testtwitterconnector.proxies.TwitterStatus createNewTweet(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "TestTwitterConnector.CreateNewTweet", params);
			return result == null ? null : testtwitterconnector.proxies.TwitterStatus.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void postTweet(IContext context, testtwitterconnector.proxies.TwitterStatus _twitterStatus)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("TwitterStatus", _twitterStatus == null ? null : _twitterStatus.getMendixObject());
			Core.execute(context, "TestTwitterConnector.PostTweet", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sendDirectMessage(IContext context, testtwitterconnector.proxies.TwitterStatus _twitterStatus)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("TwitterStatus", _twitterStatus == null ? null : _twitterStatus.getMendixObject());
			Core.execute(context, "TestTwitterConnector.SendDirectMessage", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}