// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twitterconnector.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import twitterconnector.impl.TwitterConnector;

public class SendDirectMessage extends CustomJavaAction<Boolean>
{
	private String consumerKey;
	private String consumerSecret;
	private String accessToken;
	private String accessTokenSecret;
	private String Recipient;
	private String Message;

	public SendDirectMessage(IContext context, String consumerKey, String consumerSecret, String accessToken, String accessTokenSecret, String Recipient, String Message)
	{
		super(context);
		this.consumerKey = consumerKey;
		this.consumerSecret = consumerSecret;
		this.accessToken = accessToken;
		this.accessTokenSecret = accessTokenSecret;
		this.Recipient = Recipient;
		this.Message = Message;
	}

	@Override
	public Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		TwitterConnector connector = new TwitterConnector();
		ILogNode logger = Core.getLogger(UpdateTwitterStatus.class.getName());
		connector.setLogger(logger);
		connector.sendDirectMessage(this.consumerKey, this.consumerSecret, this.accessToken, this.accessTokenSecret, this.Recipient , this.Message);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "SendDirectMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
