// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package twitterconnector.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import twitterconnector.impl.TwitterConnector;

public class UpdateTwitterStatus extends CustomJavaAction<String>
{
	private String consumerKey;
	private String consumerSecret;
	private String accessToken;
	private String accessTokenSecret;
	private String TwitterMessage;

	public UpdateTwitterStatus(IContext context, String consumerKey, String consumerSecret, String accessToken, String accessTokenSecret, String TwitterMessage)
	{
		super(context);
		this.consumerKey = consumerKey;
		this.consumerSecret = consumerSecret;
		this.accessToken = accessToken;
		this.accessTokenSecret = accessTokenSecret;
		this.TwitterMessage = TwitterMessage;
	}

	@Override
	public String executeAction() throws Exception
	{
		// BEGIN USER CODE
        TwitterConnector connector = new TwitterConnector();
        ILogNode logger = Core.getLogger(UpdateTwitterStatus.class.getName());
        connector.setLogger(logger);
        String status = connector.sendTweet(this.consumerKey, this.consumerSecret, this.accessToken, this.accessTokenSecret, this.TwitterMessage);
        return status;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "UpdateTwitterStatus";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
